name: 🔧 Enhancement / Improvement
description: Suggest improvements to existing features or UX
title: "[ENHANCEMENT] - "
labels: ["enhancement"]
assignees: []
body:
  - type: input
    id: title
    attributes:
      label: Title
      placeholder: "e.g., Improve search loading speed"
    validations:
      required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      placeholder: "Describe how the feature currently works and what’s lacking..."
    validations:
      required: true

  - type: textarea
    id: proposed_change
    attributes:
      label: Suggested Improvement
      placeholder: "Explain what should be changed and how..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context or Screenshots (optional)
      placeholder: "Include diagrams, links, or visual references if helpful..."
    validations:
      required: false

  - type: dropdown
    id: urgency
    attributes:
      label: Urgency Level
      options:
        - Low – Cosmetic or non-urgent
        - Medium – Could improve experience significantly
        - High – Needed for better performance or clarity
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: Contact Email (optional)
    validations:
      required: false

  - type: checkboxes
    id: consent
    attributes:
      label: Contact Consent
      options:
        - label: I consent to being contacted about this suggestion.
